SMW.Admin/Controllers/UserAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMW.Admin.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System.Threading.Tasks;
using SMW.EF.Models;
using System.Net;
using PagedList;
using SMW.BAL.Interface;

namespace SMW.Admin.Controllers
{
    public class UsersAdminController : Controller
    {

        SMWEntities context = new SMWEntities();
        private const int PAGESIZE = 20;
        private IUserService _userService;

        public UsersAdminController()
        {

        }

        public UsersAdminController(IUserService userService)
        {
            this._userService = userService;
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager, IUserService userService)
        {
            UserManager = userManager;
            RoleManager = roleManager;
            this._userService = userService;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        public ActionResult Index(string sortingOrder, string searchData, string Filter_Value, int? Page_No)
        {
            int Size_Of_Page = PAGESIZE;
            ViewBag.CurrentSortOrder = sortingOrder;
            ViewBag.SortingFirstName = String.IsNullOrEmpty(sortingOrder) ? "firstNameSorting" : "";
            ViewBag.SortingLastName = String.IsNullOrEmpty(sortingOrder) ? "lastNameSorting" : "";
            ViewBag.SortingUserName = String.IsNullOrEmpty(sortingOrder) ? "userNameSorting" : "";
            ViewBag.SortingPhoneNumber = String.IsNullOrEmpty(sortingOrder) ? "phoneNumberSorting" : "";
            ViewBag.SortingEmailAddress = String.IsNullOrEmpty(sortingOrder) ? "emailAddressSorting" : "";

            var searchText = string.Empty;
            if (!string.IsNullOrEmpty(searchData))
            {
                searchText = searchData.ToLower();
                Page_No = 1;
            }
            else
            {
                searchData = Filter_Value;
            }

            ViewBag.FilterValue = searchData;

            var usersx = UserManager.Users.ToList();
            var users = _userService.GetAllAdmins();
            if (users != null)
            {
                users = users.Where(u => u.FirstName.ToLower().Contains(searchText) ||
                u.LastName.ToLower().Contains(searchText)
                || u.Email.ToLower().Contains(searchText)
                || u.UserName.ToLower().Contains(searchText)).ToList();

            }

            switch (sortingOrder)
            {
                case "firstNameSorting":
                    users = users.OrderByDescending(u => u.FirstName).ToList();
                    break;
                case "lastNameSorting":
                    users = users.OrderByDescending(u => u.LastName).ToList();
                    break;
                case "userNameSorting":
                    users = users.OrderByDescending(u => u.UserName).ToList();
                    break;
                case "emailAddressSorting":
                    users = users.OrderByDescending(u => u.Email).ToList();
                    break;
                case "phoneNumberSorting":
                    users = users.OrderByDescending(u => u.PhoneNumber).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.FirstName).ToList(); ;
                    break;
            }


            int No_Of_Page = (Page_No ?? 1);
            return View(users.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        public ActionResult EstateManagers(string sortingOrder, string searchData, string Filter_Value, int? Page_No, string submit = "")
        {
            int Size_Of_Page = PAGESIZE;
            ViewBag.CurrentSortOrder = sortingOrder;
            ViewBag.SortingFirstName = String.IsNullOrEmpty(sortingOrder) ? "firstNameSorting" : "";
            ViewBag.SortingLastName = String.IsNullOrEmpty(sortingOrder) ? "lastNameSorting" : "";
            ViewBag.SortingUserName = String.IsNullOrEmpty(sortingOrder) ? "userNameSorting" : "";
            ViewBag.SortingPhoneNumber = String.IsNullOrEmpty(sortingOrder) ? "phoneNumberSorting" : "";
            ViewBag.SortingEmailAddress = String.IsNullOrEmpty(sortingOrder) ? "emailAddressSorting" : "";

            var searchText = string.Empty;
            if (!string.IsNullOrEmpty(searchData))
            {
                searchText = searchData.ToLower();
                Page_No = 1;
            }
            else
            {
                searchData = Filter_Value;
            }

            ViewBag.FilterValue = searchData;

            var usersx = UserManager.Users.ToList();
            var users = _userService.GetAllClients();
            if (users != null)
            {
                users = users.Where(u => u.FirstName.ToLower().Contains(searchText) ||
                u.LastName.ToLower().Contains(searchText)
                || u.Email.ToLower().Contains(searchText)
                || u.UserName.ToLower().Contains(searchText)).ToList();

            }

            switch (sortingOrder)
            {
                case "firstNameSorting":
                    users = users.OrderByDescending(u => u.FirstName).ToList();
                    break;
                case "lastNameSorting":
                    users = users.OrderByDescending(u => u.LastName).ToList();
                    break;
                case "userNameSorting":
                    users = users.OrderByDescending(u => u.UserName).ToList();
                    break;
                case "emailAddressSorting":
                    users = users.OrderByDescending(u => u.Email).ToList();
                    break;
                case "phoneNumberSorting":
                    users = users.OrderByDescending(u => u.PhoneNumber).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.FirstName).ToList(); ;
                    break;
            }


            int No_Of_Page = (Page_No ?? 1);
            return View(users.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.UserName,
                    Email = userViewModel.Email,
                    FirstName = userViewModel.FirstName,
                    LastName = userViewModel.LastName,
                    PhoneNumber = userViewModel.PhoneNumber
                };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);


            var userToEdit = new AdminViewModel.EditUserViewModel()
            {

SMW.Admin/Views/UsersAdmin/Create.cshtml
@model  SMW.Admin.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu" style="background-image:url(../../images/sidebar-5.jpg);" ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("admin")))
{
    <div class="content">
      
            <div id="page-title">
                <h4 class="page-header addon">Account - Create</h4>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Account</li>
            </ol>

            <div class="clear0"></div>
            <hr />


            <div class="panel panel-default panel-left">
                <div class="panel-body">

                    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <h4>Create a new account.</h4>
                        <hr />
                        @Html.ValidationSummary("", new { @class = "text-error" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            </div>
                        </div>
                         <div class="form-group">
                            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.LastName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                            </div>
                        </div>
                        
                         <div class="form-group">
                            @Html.LabelFor(m => m.PhoneNumber, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                            </div>
                        </div>
   

                        <div class="form-group">
                            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                <span style="color:#337ab7;">
                                    The Password must be at least 6 characters long, contain atleast one uppercase letter(A-Z),one lowercase letter(a-z),1 number(0-9),
                                    and one of the following characters:!@@#$%^&*()_+|~-=\{}[]:";<>?,./ Spaces are not allowed. for example AchBx$12_!
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">
                                Select User Role
                            </label>
                            <div class="col-md-10">
                                @foreach (var item in (SelectList)ViewBag.RoleId)
                                {
                                    <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                                    @Html.Label(item.Value, new { @class = "control-label" })
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn btn-default" value="Create" />
                            </div>
                        </div>
                    }

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
            </div>
            </div>
}
        </div>
   

SMW.Admin/Views/UsersAdmin/Edit.cshtml
@model  SMW.Admin.Models.AdminViewModel.EditUserViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu" style="background-image:url(../../images/sidebar-5.jpg);" ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("admin")))
{
    <div class="content">
        
            <div id="page-title">
                <h4 class="page-header addon">Account - Edit</h4>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Account</li>
            </ol>

            <div class="clear0"></div>
            <hr />


            <div class="panel panel-default panel-left">
                <div class="panel-body">

      
   
                    @using (Html.BeginForm("Edit", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.ValidationSummary("", new { @class = "text-error" })
                            @Html.HiddenFor(model => model.Id, new {@value= Model.Id  })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.FirstName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.LastName)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Roles", new { @class = "control-label col-md-2" })
                                <span class=" col-md-10">
                                    @if (Model.RolesList != null)
                                    {
                                        foreach (var item in Model.RolesList)
                                        {
                                            <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                            @Html.Label(item.Value, new { @class = "control-label" })
                                        }
                                    }                                 
                                </span>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
            </div>
    </div>
}
</div>

SMW.Admin/Views/UsersAdmin/Index.cshtml
@model PagedList.IPagedList<SMW.Models.AspNetUser>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu" style="background-image:url(../../images/sidebar-5.jpg);" ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("admin")))
{
    <div class="content">
        

            <div id="page-title">
                <h4 class="page-header addon">Accounts</h4>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Administrators</li>
            </ol>

            <div class="clear0"></div>
            <hr />

        <tabset>
          
            <tab class="active">
                <tab-heading>
                    <input name="submit" type="submit" id="parent" value="Admins" onclick="location.href='@Url.Action("Index", "UsersAdmin")'" />
                </tab-heading>
                <div class="panel panel-default panel-left">
                    <div class="panel-body">
                        <p>
                            <a href="/UsersAdmin/create" class="btn btn-default">
                                <i class="fa fa-fw fa-user"></i>
                                Add a new user
                            </a>
                        </p>

                        @using (Html.BeginForm("Index", "UsersAdmin", FormMethod.Get))
                        {
                            <span>Search for a user using his/her username, first name, last name or email address.</span>
                            <p>
                                Search User: @Html.TextBox("searchData", ViewBag.FilterValue as string)
                                <input type="submit" value="Find" />
                            </p>

                        }
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <tr>
                                    <th>
                                        @Html.ActionLink("UserName", "Index", new { sortingOrder = ViewBag.SortingUserName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("First Name", "Index", new { sortingOrder = ViewBag.SortingFirstName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Last Name", "Index", new { sortingOrder = ViewBag.SortingLastName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Email Address", "Index", new { sortingOrder = ViewBag.SortingEmailAddress, Filter_Value = ViewBag.FilterValue })

                                    </th>
                                    <th>
                                        @Html.ActionLink("Phone Number", "Index", new { sortingOrder = ViewBag.SortingPhoneNumber, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        Actions
                                    </th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LastName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                                        </td>

                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }

                            </table>
</div>
                            <br />
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                            @Html.PagedListPager(Model, Page_No => Url.Action("Index",
                    new { Page_No, Sorting_Order = ViewBag.CurrentSortOrder, Filter_Value = ViewBag.FilterValue }))
                        </div>
                </div>

            </tab>
            <tab>
                <tab-heading>
                    <input name="submit" type="submit" id="parent" value="Managers" onclick="location.href='@Url.Action("EstateManagers", "UsersAdmin", new { submit = "manager" })'" />
                </tab-heading>
                <div class="panel panel-default panel-left">
                    <div class="panel-body">
                        <p>
                            <a href="/UsersAdmin/create" class="btn btn-default">
                                <i class="fa fa-fw fa-user"></i>
                                Add a new user
                            </a>
                        </p>

                        @using (Html.BeginForm("EstateManagers", "UsersAdmin", FormMethod.Get))
                        {
                            <span>Search for a user using his/her username, first name, last name or email address.</span>
                            <p>
                                Search User: @Html.TextBox("searchData", ViewBag.FilterValue as string)
                                <input type="submit" value="Find" />
                            </p>

                        }
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <tr>
                                    <th>
                                        @Html.ActionLink("UserName", "Index", new { sortingOrder = ViewBag.SortingUserName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("First Name", "Index", new { sortingOrder = ViewBag.SortingFirstName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Last Name", "Index", new { sortingOrder = ViewBag.SortingLastName, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        @Html.ActionLink("Email Address", "Index", new { sortingOrder = ViewBag.SortingEmailAddress, Filter_Value = ViewBag.FilterValue })

                                    </th>
                                    <th>
                                        @Html.ActionLink("Phone Number", "Index", new { sortingOrder = ViewBag.SortingPhoneNumber, Filter_Value = ViewBag.FilterValue })
                                    </th>
                                    <th>
                                        Actions
                                    </th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LastName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                                        </td>

                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }

                            </table>
                            </div>
                            <br />
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                            @Html.PagedListPager(Model, Page_No => Url.Action("Index",
                    new { Page_No, Sorting_Order = ViewBag.CurrentSortOrder, Filter_Value = ViewBag.FilterValue }))
                        </div>
                </div>

            </tab>

        </tabset>
            
        </div>
 }
    </div>